<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'f6ac67aaed5f1363de635c2dd2ca036b',
  'DATABASE_URL' => 'mysql://root:root@127.0.0.1:3306/basica_portfolio',
  'MAILER_URL' => 'null://localhost',
);
